//for Authentication
export const SIGN_IN="SIGN_IN"
export const SIGN_IN_SUCCESS="SIGN_IN_SUCCESS"
export const SIGN_IN_ERROR="SIGN_IN_FAIL"

export const SET_AUTHENTICATED_USER="SET_AUTHENTICATED_USER"
export const CHECKING_AUTHENTICATED_USER="CHECKING_AUTHENTICATED_USER"
export const SIGN_OUT="SIGN_OUT"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE"

//for Attempting Paper
export const FETCH_PAPER="FETCH_PAPER"
export const FETCH_PREVIOUS_ANSWERS="FETCH_PREVIOUS_ANSWERS"
export const SET_SEEN="SET_SEEN"
export const SET_ANSWER="SET_ANSWER"
export const CLEAR_ANSWER="CLEAR_ANSWER"
export const BOOKMARK_QUESTION="BOOKMARK_QUESTION"
export const ATTEMPT_SUBJECTIVE="ATTEMPT_SUBJECTIVE"